language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.1

script:
  # Run a new console app
  - dotnet restore
  - dotnet build
  - dotnet run --project ./tests/SentimentFS.Text.Tests/SentimentFS.Text.Tests.fsproj